language: python
python:
  - "3.7"
# OS Compatibility
os:
  - windows
  - linux
  - osx
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest