language: python
python:
  - "3.7"
# OS Compatibility
os:
  - windows
  - linux
  - osx
# command to install dependencies
install:
  - pipenv install 
# command to run tests
script:
  - pipenv run python pytest