language: python
python:
  - "3.7"
# OS Compatibility
os:
  - windows
  - linux
  - osx
# command to install dependencies
install:
  - pipenv install codecov
# command to run tests
script:
  - pipenv run python pytest
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: 576c47f63b64e80b364099b86c8177892fa82c95
  keep-history: true
  on:
    branch: master
# Push the results back to codecov
after_success:
  - codecov
